all:
  children:
    webservers:
      hosts:
        Web1:
          ansible_host: 192.168.56.50
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/Web1/virtualbox/private_key
          ansible_user: vagrant
          http_port: 8080
        Web2:
          ansible_host: 192.168.56.51
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/Web2/virtualbox/private_key
          ansible_user: vagrant
          http_port: 8081
    databases:
      hosts:
        DB:
          ansible_host: 192.168.56.52
          ansible_port: 22
          ansible_ssh_private_key_file: .vagrant/machines/DB/virtualbox/private_key
          ansible_user: vagrant